name: Deploy to Server

on:
  push:
    branches:
      - main  # Deploy khi có push lên main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/your-repo
            git pull origin main
            npm install  # Nếu dùng Node.js
            pm2 restart all  # Restart ứng dụng (Node.js)
